name: Check Terraform Format
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Terraform format check
        uses: docker://hashicorp/terraform:1.7.5 fmt -recursive -check
